[package]
name = "query-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
query-core = { path = "../query-core" }
thiserror.workspace = true
